name: triggering_code

on: 
   push:  
        paths:
            - '**'

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:

        - id: file_changes
          if: github.event_name == 'push'
          uses: trilom/file-changes-action@v1.2.3
        - name: files
          if: github.event_name == 'push'
          id: check-modifications
          run: |
            cat $HOME/files.json
            cat $HOME/files_modified.json
            cat $HOME/files_added.json
            echo '${{ steps.file_changes.outputs.files}}'
            echo '${{ steps.file_changes.outputs.files_modified}}'
            echo '${{ steps.file_changes.outputs.files_added}}'

        - name: Get Token
          id: get_workflow_token
          uses: tibdex/github-app-token@v1
          with:
            private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
            app_id: ${{ secrets.APPLICATION_ID }}
            repository: icub-tech-iit/code
            
        # - name: Repository dispatch to code
        #   uses: peter-evans/repository-dispatch@v1
        #   env:
        #     GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        #   with:
        #     token: ${{ env.GITHUB_APPS_TOKEN }}
        #     repository: icub-tech-iit/code
        #     event-type: repository_trigger
        #     client-payload: '{"type": "repository_trigger", "img_list": "human-sensing"}'

       
             